### ISSUE TITLE
Error: lstm_1_input to have 3 dimensions, but got array with shape (0, 30)

### ISSUE THREAD

**Issue by Keremtspnr** [jahyeha/capstone-project#2]
Hello there. I clonned the project and tried as description.txt. But i got error like this when i run lstm.py.

> Traceback (most recent call last):
>   File "C:/Users/Kerem/Desktop/senkrondata/product-matching-model/lstm.py", line 128, in <module>
>     lstm.run_lstm(max_seq_len=max_seq_len)
>   File "C:/Users/Kerem/Desktop/senkrondata/product-matching-model/lstm.py", line 37, in run_lstm
>     history = model.fit(X_train, Y_train, epochs=20, batch_size=100, verbose=1, validation_data=(X_val, Y_val))
>   File "C:\Users\Kerem\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\training.py", line 972, in fit
>     batch_size=batch_size)
>   File "C:\Users\Kerem\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\training.py", line 751, in _standardize_user_data
>     exception_prefix='input')
>   File "C:\Users\Kerem\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\training_utils.py", line 128, in standardize_input_data
>     'with shape ' + str(data_shape))
> ValueError: Error when checking input: expected lstm_1_input to have 3 dimensions, but got array with shape (0, 30)

**Comment by ranjith-b** [comment]
Hi there ! got the similar error as @Keremtspnr  has pointed out.  Any suggestions ?
```
$ python lstm.py
Using TensorFlow backend.
✱ Run LSTM model...
--------------------------------------
train: 1 | val: 0 | test: 1
--------------------------------------
Traceback (most recent call last):
  File "lstm.py", line 131, in <module>
    lstm.run_lstm(max_seq_len=max_seq_len) # run& save my LSTM model
  File "lstm.py", line 40, in run_lstm
    history = model.fit(X_train, Y_train, epochs=20, batch_size=100, validation_data=(X_val, Y_val))
  File "/Users/ranjith/opt/anaconda3/envs/pm/lib/python3.6/site-packages/keras/engine/training.py", line 972, in fit
    batch_size=batch_size)
  File "/Users/ranjith/opt/anaconda3/envs/pm/lib/python3.6/site-packages/keras/engine/training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "/Users/ranjith/opt/anaconda3/envs/pm/lib/python3.6/site-packages/keras/engine/training_utils.py", line 128, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected lstm_1_input to have 3 dimensions, but got array with shape (0, 30)
```
